[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
persona_nft = "JARiuuCE7xEkfk99bfQPQvJBjfY3btMxTuEKQ8ArzfQ9"
social_graph = "EmKvmnfXrcgmcj4yT2K12rM2dMTZS2MMAfUB8769veHK"
trust_score = "3FWDkwEPfVVZmxXS4f3pDaJpg4qf7GL5ir89DtXSwAjR"

[programs.mainnet]
persona_nft = "11111111111111111111111111111111"
social_graph = "11111111111111111111111111111111"
trust_score = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/persona-nft", "programs/trust-score", "programs/social-graph"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
