name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint
        run: npm run lint --if-present
      
      - name: Format check
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json,md}"

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./api
        run: npm install
      
      - name: Run tests
        working-directory: ./api
        run: npm test --if-present

  test-mobile:
    name: Test Mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./mobile
        run: npm install --legacy-peer-deps
      
      - name: Run tests
        working-directory: ./mobile
        run: npm test --if-present

  build-programs:
    name: Build Anchor Programs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli --locked
      
      - name: Build programs
        run: anchor build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          path: target/deploy/

  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install API dependencies
        working-directory: ./api
        run: npm install
      
      - name: TypeScript check (API)
        working-directory: ./api
        run: npx tsc --noEmit
      
      - name: Install Mobile dependencies
        working-directory: ./mobile
        run: npm install --legacy-peer-deps
      
      - name: TypeScript check (Mobile)
        working-directory: ./mobile
        run: npx tsc --noEmit




